if(EXISTS "/home/flow/Documents/vsc/FIIT_SP/allocator/build1/allocator_global_heap/tests/sys_prog_allctr_allctr_glbl_hp_tests[1]_tests.cmake")
  include("/home/flow/Documents/vsc/FIIT_SP/allocator/build1/allocator_global_heap/tests/sys_prog_allctr_allctr_glbl_hp_tests[1]_tests.cmake")
else()
  add_test(sys_prog_allctr_allctr_glbl_hp_tests_NOT_BUILT sys_prog_allctr_allctr_glbl_hp_tests_NOT_BUILT)
endif()
